### ISSUE TITLE
项目里面没有 androidutils 模块 ??

### ISSUE THREAD

**Issue by SteveXiaoyong** [D-clock/AndroidAlbum#3]
![nnn](https://cloud.githubusercontent.com/assets/17610430/14230792/fa1ca808-f998-11e5-87a3-8a096c24ab1f.png)

**Comment by D-clock** [comment]
@SteveXiaoyong 在readme里面已经详细说明了 androidutils 在 https://github.com/D-clock/AndroidUtils
