### ISSUE TITLE
我用的是androidstudio1.5.1,怎么导入有错误：

### ISSUE THREAD

**Issue by geogie** [D-clock/AndroidAlbum#5]
Error:(1, 0) Plugin with id 'com.android.application' not found.
<a href="openFile:E:\soft\leshiTV\AndroidAlbum-master\build.gradle">Open File</a>

**Comment by D-clock** [comment]
@geogie 估计是gradle原因，具体你要自己排查！

**Comment by geogie** [comment]
我看了下是我的androidstudio项目结构结构和你的不一样,不知道怎么转化成，你的androidstudio是那个版本的?
![Uploading image.png…]()

**Comment by D-clock** [comment]
？没看到你的截图？我as是1.5.3的，这个没关系吧！

**Comment by D-clock** [comment]
@geogie ？没看到你的截图？我as是1.5.3的，这个没关系吧！

**Comment by geogie** [comment]
和其他gitbub 里的项目结构不太一样，我又发给你邮件，帮忙看下，哈哈
