### ISSUE TITLE
import com.clock.utils.crash.CrashExceptionHandler;

### ISSUE THREAD

**Issue by SSourceFile** [D-clock/AndroidAlbum#6]
import com.clock.utils.crash.CrashExceptionHandler;,所谓的utils没找到。。。。求指导

**Comment by D-clock** [comment]
你没有引入[AndroidUtils](https://github.com/D-clock/AndroidUtils)作为依赖工程吧，这个类在这里啊：https://github.com/D-clock/AndroidUtils/tree/master/src/main/java/com/clock/utils/crash

**Comment by D-clock** [comment]
@huaminghui  你没有引入[AndroidUtils](https://github.com/D-clock/AndroidUtils)作为依赖工程吧，这个类在这里啊：https://github.com/D-clock/AndroidUtils/tree/master/src/main/java/com/clock/utils/crash
