### ISSUE TITLE
特别建议请好好整理下这个项目 ，最外层build.gradle没有，然后aar包也一直导不进去

### ISSUE THREAD

**Issue by tracyliu1** [D-clock/AndroidAlbum#9]

**Comment by tracyliu1** [comment]
![image](https://cloud.githubusercontent.com/assets/17140629/18198120/78c8f3da-712d-11e6-9718-5f9c818bf812.png)

**Comment by D-clock** [comment]
@tracyliu1 以前上传项目的时候没注意，刚刚更新了build.gradle，你试试？

**Comment by tracyliu1** [comment]
![_20160902175242](https://cloud.githubusercontent.com/assets/17140629/18200448/78735542-7137-11e6-8923-54299b98506c.png)
Junit  和 bugly不行，把这些相关删掉之后，终于能跑了。。。 这最初是个eclipse工程吧，做为渣渣不太懂

**Comment by tracyliu1** [comment]
之前的我是手动拽过来一个外层build.gradle，最后卡在了AndroidUtils  和 photoview 的aar上

**Comment by D-clock** [comment]
这个一开始就 AS 工程，我再看看，调整下。

**Comment by zhuzhaolin** [comment]
最外层的build.gradle还是没有，诚心要求作者好好整理一下这个项目。

**Comment by D-clock** [comment]
已经做了整理，这回直接打开Project就行了。大家可以试试。
